### PR TITLE
A couple of fixes

### LINKED ISSUE #26: Ignore floating or hidden window
I have floating and hidden window, can you resize the parent of the floating or hidden window to match to the other one? like this

Tiled

```
_______________
|        |    |
|        |----|
|        | xx |
|        |----|
|________|____|

```

Floating or Hidden

```
_______________
|        |    |
|        |    |
|        |    |
|        |----|
|________|____|

```

What i want

```
_______________
|        |    |
|        |    |
|        |----|
|        |    |
|________|____|

```

### PR DESCRIPTION
**Pull request by darkelectron**

### CODE REVIEW

**Review by phenax — APPROVED** [review]

**Comment by phenax** [comment]
@darkelectro I'm currently unable to test the fix out. Will merge once that's done.

**Comment by darkelectron** [comment]
Alright. Forgot to mention that this may resolve #20 

Worked without the `--master-size` on my end.

**Comment by A-Siam** [comment]
@darkelectron does it need any special configuration? because it seems to keep the same issue on my machine https://streamable.com/6vzuy0
Sorry about the noise 😅

**Comment by darkelectron** [comment]
This new PR fixes #12. 
It recalculates whenever one focuses on that particular desktop.

**Comment by darkelectron** [comment]
ping @phenax

**Comment by darkelectron** [comment]
I think it depends on the floating app. Haven't been able to reproduce though.

**Review by phenax — CHANGES_REQUESTED** [review]
Doesn't seem to have fixed the floating issue. The problem with floating windows is that they aren't being ignored in the layout.

**Comment by a2n-s** [comment]
> Doesn't seem to have fixed the floating issue.
>
i confirm that the problem still is present.
i do not have the exact same bug as in #20, but the floating window sometimes gets included in the background tilling :thinking: 

see [this clip](https://imgur.com/a/rqmnGXV)
the last floating window, when removing the main window in the `rtall` layout,, i.e. the one to the right labeled "monferno", gets squished to the right as if it was the new main frame

**Comment by a2n-s** [comment]
and apart from that, i have to admit i'm not sure what this PR is doing...

@darkelectron, do you still have in mind what you wanted to do here? that would be really great to help me figure out why the floating bug isn't resolved :yum:

**Comment by a2n-s** [comment]
Hi @darkelectron :wave: :yum: 

as this PR has ben stale for more than a year now, we've decided with @phenax to move the changes to [a2n-s/ignore](https://github.com/a2n-s/bsp-layout/tree/ignore) and apply the requested changes there :+1: 

hope you'll understand :wink:

**Pull request closed without merging**
